name = input("Lijule")
print("Hello " + Lijule)
age = input("13")
addr = input("Iligan")
print(Lijule + "Bayanihan Village Barangay Santa Elena" + addr)
year = 2026 - int(age)
print("Born in:" + str(year))
